name: 🐛 Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: requested_by_name
    attributes:
      label: Requested By
      placeholder: ex. Tester Name
    validations:
      required: true
  - type: input
    id: requested_by_email
    attributes:
      label: Requested By Email
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: dropdown
    id: team
    attributes:
      label: Team
      multiple: false
      options:
        - Marketing
        - Contents
        - Design
        - QA
        - Sales
    validations:
      required: true
  - type: checkboxes
    id: stage
    attributes:
      label: Stage
      description: Check stages where you are having this issue
      options:
        - label: INT
        - label: STG
        - label: PRD
  - type: checkboxes
    id: project
    attributes:
      label: Projects
      description: Check projects where you are having this issue
      options:
        - label: ICH - Website
        - label: ICH - Admin
        - label: B2B - tech.icloudhospital.com
        - label: SaaS Client - Website
        - label: SaaS Client - Admin
  - type: dropdown
    id: device
    attributes:
      label: What device are you seeing the problem on?
      multiple: true
      options:
        - iPhone (iOS)
        - Android (AOS)
        - Windows OS
        - Mac OS
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
  - type: input
    id: os_browser_version
    attributes:
      label: OS | Browser Version
      placeholder: ex. iOS 17.1
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior
      placeholder: Tell us what happened
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
