name: 🐞 Bug report
description: Create a report to help us improve
# title: ""
labels: ["bug"]
# assignees: ""

body:
  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      description: ❗️REQUIRED
      options:
        - label: PRD
        - label: INT

  - type: checkboxes
    id: project-type
    attributes:
      label: Project Type
      description: ❗️REQUIRED
      options:
        - label: ICH - Website
        - label: ICH - Admin
        - label: ICH - Android
        - label: ICH - iOS
        - label: SaaS Client - Website
        - label: SaaS Client - Admin

  - type: textarea
    attributes:
      label: Desktop
      value: |
        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]
    validations:
      required: false

  - type: textarea
    attributes:
      label: Smartphone
      value: |
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser [e.g. stock browser, safari]
        - Version [e.g. 22]
    validations:
      required: false

  - type: input
    id: figma-link
    attributes:
      label: Figma - Design Link
      description: "Add figma file link here for better understanding for the engineers, if applicable."
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.

  - type: textarea
    attributes:
      label: Reproduction Steps?
      description: |
        Steps to reproduce the behavior:
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshot or ScreenRecording
      description: A clear & very short media (photo or video) of the bug has to be provided here for clear understanding.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Please check if `Assignees` is specified.
