name: 🚀 Feature request
description: Suggest an idea for this project or Ask QA to test
# title: ""
labels: ["enhancement"]
# assignees: ""

body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: If the priority is high, add `High priority` to the label.
      options:
        - High
        - Medium
        - Row
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## 🟢 For test requests
        > If you want to ask QA to test, Please check environment.
        Otherwise, you can ignore the environment field.

  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      options:
        - label: PRD
        - label: INT
    validations:
      required: false

  - type: markdown
    attributes:
      value: ---

  - type: checkboxes
    id: project-type
    attributes:
      label: Project Type
      description: ❗️REQUIRED
      options:
        - label: ICH - Website
        - label: ICH - Admin
        - label: ICH - Android
        - label: ICH - iOS
        - label: SaaS Client - Website
        - label: SaaS Client - Admin
    validations:
      required: true

  - type: textarea
    attributes:
      label: Is your proposal related to a problem?
      description: |
        Provide a clear and concise description of what the problem is.
        For example, "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    attributes:
      label: Requirement - Describe the solution you'd like
      description: Provide a clear and concise description of what you want to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: Let us know about other solutions you've tried or researched.

  - type: input
    id: figma-link
    attributes:
      label: Figma Link
      description: "Add a figma link page if the problem is already solved in terms of UX/UI"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Is there anything else you can add about the proposal?
        You might want to link to related issues here, if you haven't already.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        1. Please check if `Assignees` is specified.
        2. If you want to ask QA to test, set the label to `help wanted`, `test request`.
